const ActionTypes = {
    GET_REGION : 'GET_REGION',
    GET_REGION_SUCCEED : 'GET_REGION_SUCCEED',
    GET_REGION_FAILED : 'GET_REGION_FAILED',
    ADD_REGION : 'ADD_REGION',
    ADD_REGION_SUCCEED : 'ADD_REGION_SUCCEED',
    ADD_REGION_FAILED : 'ADD_REGION_FAILED',
    UPDATE_REGION : 'UPDATE_REGION',
    UPDATE_REGION_SUCCEED : 'UPDATE_REGION_SUCCEED',
    UPDATE_REGION_FAILED : 'UPDATE_REGION_FAILED',
    DEL_REGION : 'DEL_REGION',
    DEL_REGION_SUCCEED : 'DEL_REGION_FAILED',
    DEL_REGION_FAILED : 'DEL_REGION_FAILED'
}

export default ActionTypes